#!/bin/sh
# Alden's first i3block! :)

#dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'

echo "$(playerctl metadata artist)" "|" "$(playerctl metadata title)"
