#!/bin/bash
NOTE_DIR_NAME=$(ls $HOME/Notes/ | grep -v "\." | rofi -dmenu -i -p "Select Note to Edit")
NOTE_DIR=$HOME/Notes/$NOTE_DIR_NAME
if  [ ! -d "$NOTE_DIR" ]
then
   mkdir $NOTE_DIR
   figlet $NOTE_DIR_NAME > $NOTE_DIR/note.md
fi
vim $NOTE_DIR/note.md
