#!/bin/sh
notify-send -t 1 "Please drag your mouse over the screenshot selection" &
pkill escrotum
escrotum -s "/tmp/mostrecentscrot.png"  #|  tr -s '[[:punct:][:space:]]' '\n' |  sed -n 's/[^0-9]*//p' | xargs -n1 notify-send -u normal
NEW_NAME=`dmenu -i -p "Set File Name"`
if [[ $NEW_NAME != *.png ]] 
then
    NEW_NAME="$NEW_NAME.png"
fi
SHOT_DIR=$HOME/Photos/screenshots/`ls ~/Photos/screenshots | grep -v "\." | dmenu -i -p "Select Dir to save to"` 
if  [ ! -d "$SHOT_DIR" ]
then
   mkdir $SHOT_DIR
fi
FILE_LOCATION=$SHOT_DIR/$NEW_NAME
mv /tmp/mostrecentscrot.png $FILE_LOCATION
# Allow us to mark the file if the screenshot didn't come out right and delete it upon sxiv exit
sxiv -o $FILE_LOCATION | xargs -I{} rm {}
if [[ -e $FILE_LOCATION ]]
then
    xclip -selection clipboard -t image/png -i $FILE_LOCATION
fi
