#!/bin/bash

DIR=$(ls ~/Photos/screenshots | grep -v "\." | rofi -dpi 1 -dmenu -i -p "Select Screenshots to View")
# Debugging bash
# set -x
if [ -n "$DIR" ]
then
    IMAGE=$(sxiv -fto $(find /home/alden/Photos/screenshots/$DIR -maxdepth 1 -type f))
    if [[ $IMAGE == */alden/*/alden/* ]] 
    then
        prompt "You have selected multiple photos, would you like to delete them?" "rm $IMAGE"
    elif [[ -e "$IMAGE" ]] 
    then
        notify-send "$IMAGE copied to clipboard"  
        xclip -selection clipboard -t image/png -i $IMAGE
    fi
fi
